name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' si tu rama principal se llama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Pages Artifact
      run: mkdir -p public && cp -r * public

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: public

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1